repos:
-   repo: https://github.com/ambv/black
    rev: 20.8b1
    hooks:
    - id: black
      exclude: ^tmp/
      language_version: python3.10
      additional_dependencies: ['click==8.0.4']
-   repo: https://github.com/PyCQA/flake8
    rev: 3.7.9
    hooks:
    - id: flake8
      exclude: ^tmp/
      language_version: python3.10
      args: ['--max-line-length=88', '--extend-ignore=E203']
-   repo: local
    hooks:
    - id: jupyter-nb-clear-output
      name: jupyter-nb-clear-output
      files: \.ipynb$
      stages: [commit]
      language: system
      entry: jupyter nbconvert --Exporter.preprocessors "preprocess.CustomClearOutputPreprocessor" --inplace
